# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

language: objective-c
osx_image: xcode8
# cache: cocoapods

podfile: Example/Podfile

before_install:
	- gem install cocoapods # Since Travis is not always on latest version
	- pod install --project-directory=Example

install:
	- ./swift-lint.sh

script:
	- set -o pipefail && xcodebuild test -workspace Example/SwiftSpec.xcworkspace -scheme SwiftSpec-Example -sdk iphonesimulator9.3 ONLY_ACTIVE_ARCH=NO | xcpretty
	- pod lib lint

after_success:
	- bash <(curl -s https://codecov.io/bash) -J 'SwiftSpec'
